consumes:
- application/json
definitions:
  CodeRequest:
    properties:
      name:
        description: Code name.
        example: firewall
        type: string
      source:
        description: Code source
        type: string
    required:
    - name
    - source
    type: object
  CodeResponse:
    properties:
      results:
        items:
          $ref: '#/definitions/CodeResultResponse'
        type: array
      when:
        description: Datetime of the configuration changes.
        example: 2020/02/13 15:27:06
        format: date-time
        type: string
    required:
    - results
    - when
    type: object
  CodeResultResponse:
    properties:
      warning:
        description: Warning message.
        example: 'Useless properties: id'
        type: string
    type: object
  ConfigActionRequest:
    properties:
      args:
        description: Single command argument.
        example: -al
        type: string
      cmd:
        description: Command.
        type: string
      daemon:
        description: Key used to execute the command as daemon.
        example: firewall
        type: string
    required:
    - cmd
    type: object
  ConfigParameterRequest:
    properties:
      path:
        items:
          description: Key path.
          example: period
          type: string
        type: array
      schema:
        description: Scheme.
        enum:
        - json
        - yaml
        - properties
        example: yaml
        type: string
      source:
        description: Source filename.
        example: filebeat.yml
        type: string
      value:
        description: Parameter new value.
        example: 10s
        type: string
    required:
    - schema
    - source
    - value
    type: object
  ConfigRequest:
    properties:
      actions:
        description: List of actions.
        items:
          $ref: '#/definitions/ConfigActionRequest'
        type: array
      parameters:
        description: List of parameters.
        items:
          $ref: '#/definitions/ConfigParameterRequest'
        type: array
      resources:
        description: List of resources.
        items:
          $ref: '#/definitions/ConfigResourceRequest'
        type: array
    type: object
  ConfigResourceRequest:
    properties:
      content:
        description: Resource content.
        type: string
      path:
        description: File path
        example: filebeat.yml
        type: string
    required:
    - content
    - path
    type: object
  ConfigResponse:
    properties:
      results:
        items:
          $ref: '#/definitions/ConfigResultResponse'
        type: array
      when:
        description: Datetime of the configuration changes
        example: 2020/02/13 15:27:06
        format: date-time
        type: string
    required:
    - results
    - when
    type: object
  ConfigResultResponse:
    properties: {}
    type: object
  HTTPError:
    properties:
      description:
        description: Human readable message that describes the error.
        example: The request body is not a valid JSON or it is not encoded as UTF-8.
        type: string
      title:
        description: Title error
        example: 400 Bad Request
        type: string
    required:
    - description
    - title
    type: object
  StatusResponse:
    properties:
      id:
        description: ID of the execution environment.
        example: apache
        type: string
      last_heartbeat:
        description: Timestamp of the expiration of the API access configuration.
        example: 2019/02/14 15:23:33
        format: date-time
        type: string
      password:
        description: Password for the CB to connect to this LCP.
        type: string
      started:
        description: Timestamp when the LCP is started
        example: 2019/02/14 15:23:30
        format: date-time
        type: string
      username:
        description: Username for the CB to connect to this LCP.
        type: string
    required:
    - id
    - last_heartbeat
    - started
    type: object
info:
  title: Local Control Plane
  version: 097b2b58c99c7151fa0c82639abe940cde56c436@master
paths:
  /code/{id}:
    delete:
      description: Inject code at run-time in the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/CodeRequest'
          type: array
      responses:
        '200':
          description: Code injection executed.
          schema:
            $ref: '#/definitions/CodeResponse'
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/HTTPError'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Code injection
      tags:
      - code
    post:
      description: Inject code at run-time in the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/CodeRequest'
          type: array
      responses:
        '200':
          description: Code injection executed.
          schema:
            $ref: '#/definitions/CodeResponse'
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/HTTPError'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Code injection
      tags:
      - code
    put:
      description: Update the injected code at run-time in the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/CodeRequest'
          type: array
      responses:
        '200':
          description: Code injection executed.
          schema:
            $ref: '#/definitions/CodeResponse'
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/HTTPError'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Update injected code
      tags:
      - code
  /config:
    post:
      description: Apply configuration changes to the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/ConfigRequest'
          type: array
      responses:
        '200':
          description: Configuration changes executed.
          schema:
            items:
              $ref: '#/definitions/ConfigResponse'
            type: array
        '400':
          description: Bad request.
          schema:
            $ref: '#/definitions/HTTPError'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Configuration update
      tags:
      - config
  /status:
    get: {}
    post:
      description: Set the last heartbeat.
      responses:
        '200':
          description: Status data of the LCP.
          schema:
            $ref: '#/definitions/StatusResponse'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Status set.
      tags:
      - status
produces:
- application/json
swagger: '2.0'
tags:
- description: Code injection at run-time.
  name: code
- description: Configuration at run-time.
  name: config
- description: Status data of the LCP.
  name: status
