consumes:
- application/json
definitions:
  Code_Request_:
    properties:
      name:
        description: Code name.
        example: firewall
        type: string
      source:
        description: Code source
        type: string
    required:
    - name
    - source
    type: object
  Code_Response_:
    properties:
      results:
        items:
          $ref: '#/definitions/Code_Result_Response_'
        type: array
      when:
        description: Datetime of the configuration changes.
        example: 2020/02/13 15:27:06
        format: date-time
        type: string
    required:
    - results
    - when
    type: object
  Code_Result_Response_:
    properties:
      warning:
        description: Warning message.
        example: 'Useless properties: id'
        type: string
    type: object
  Config_Action_Request_:
    properties:
      args:
        description: Single command argument.
        example: -al
        type: string
      cmd:
        description: Command.
        type: string
      daemon:
        description: Key used to execute the command as daemon.
        example: firewall
        type: string
      id:
        description: Id of the action.
        example: start
        type: string
    required:
    - cmd
    - id
    type: object
  Config_Parameter_Request_:
    properties:
      id:
        description: Id of the parameter.
        example: period
        type: string
      path:
        items:
          description: Key path.
          example: period
          type: string
        type: array
      schema:
        description: Scheme.
        enum:
        - json
        - properties
        - xml
        - yaml
        example: yaml
        type: string
      source:
        description: Source filename.
        example: firewall.xml
        type: string
      value:
        description: Parameter new value.
        example: 10s
        type: string
    required:
    - id
    - schema
    - source
    - value
    type: object
  Config_Request_:
    properties:
      actions:
        description: List of actions.
        items:
          $ref: '#/definitions/Config_Action_Request_'
        type: array
      parameters:
        description: List of parameters.
        items:
          $ref: '#/definitions/Config_Parameter_Request_'
        type: array
      resources:
        description: List of resources.
        items:
          $ref: '#/definitions/Config_Resource_Request_'
        type: array
    type: object
  Config_Resource_Request_:
    properties:
      content:
        description: Resource content.
        type: string
      id:
        description: Id of the resource.
        example: filebeat-config
        type: string
      path:
        description: File path
        example: firewall.xml
        type: string
    required:
    - content
    - id
    - path
    type: object
  Config_Response_:
    properties:
      error:
        description: Indicate the presence of an error.
        example: true
        type: boolean
      type:
        description: Type of the response.
        enum:
        - action
        - parameter
        - resource
        example: action
        type: string
    type: object
  Status_Response_:
    properties:
      id:
        description: ID of the execution environment.
        example: apache
        type: string
      last_heartbeat:
        description: Timestamp of the expiration of the API access configuration.
        example: 2019/02/14 15:23:33
        format: date-time
        type: string
      password:
        description: Password for the CB to connect to this LCP.
        type: string
      started:
        description: Timestamp when the LCP is started
        example: 2019/02/14 15:23:30
        format: date-time
        type: string
      username:
        description: Username for the CB to connect to this LCP.
        type: string
    required:
    - id
    - last_heartbeat
    - started
    type: object
info:
  title: Local Control Plane
  version: 7b358d78660d0b524f43218a0fda414fa7f3c239@master
paths:
  /code/{id}:
    delete:
      description: Inject code at run-time in the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/Code_Request_'
          type: array
      responses:
        '200':
          description: Code injection executed.
          schema:
            $ref: '#/definitions/Code_Response_'
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/Code_Response_'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/Code_Response_'
      summary: Code injection
      tags:
      - code
    post:
      description: Inject code at run-time in the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/Code_Request_'
          type: array
      responses:
        '200':
          description: Code injection executed.
          schema:
            $ref: '#/definitions/Code_Response_'
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/Code_Response_'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/Code_Response_'
      summary: Code injection
      tags:
      - code
    put:
      description: Update the injected code at run-time in the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/Code_Request_'
          type: array
      responses:
        '200':
          description: Code injection executed.
          schema:
            $ref: '#/definitions/Code_Response_'
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/Code_Response_'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/Code_Response_'
      summary: Update injected code
      tags:
      - code
  /config:
    post:
      description: Apply configuration changes to the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/Config_Request_'
          type: array
      responses:
        '200':
          description: Configuration changes executed.
          schema:
            items:
              $ref: '#/definitions/Config_Response_'
            type: array
        '400':
          description: Bad request.
          schema:
            $ref: '#/definitions/Config_Response_'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/Config_Response_'
      summary: Configuration update
      tags:
      - config
  /status:
    get:
      description: Get info about the status of the LCP in the execution environment.
      responses:
        '200':
          description: Status data of the LCP.
          schema:
            $ref: '#/definitions/Status_Response_'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/Code_Response_'
      summary: Status info
      tags:
      - status
    post:
      description: Set the last heartbeat.
      responses:
        '200':
          description: Status data of the LCP.
          schema:
            $ref: '#/definitions/Status_Response_'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/Code_Response_'
      summary: Status set.
      tags:
      - status
produces:
- application/json
swagger: '2.0'
tags:
- description: Code injection at run-time.
  name: code
- description: Configuration at run-time.
  name: config
- description: Status data of the LCP.
  name: status
