Apply configuration changes to the local environment.
---
summary: Configuration update
description: Apply configuration changes to the local environment.
tags: [config]
parameters:
  - name: payload
    required: true
    in: body
    schema:
      type: array
      items: Config_Request_Schema
responses:
  200:
    description: Configuration changes executed.
    schema:
      type: array
      items: Config_Response_Schema
  400:
    description: Bad request.
    schema: Config_Response_Schema
  401:
    description: Unauthorized.
    schema: Config_Response_Schema
